# Generated by Django 5.2 on 2025-05-22 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.category'),
        ),
    ]
