# Generated by Django 5.0.7 on 2025-05-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_rate_event_rated_rate'),
        ('events', '0005_alter_event_created_at'),
    ]

    operations = [
    ]
