# Generated by Django 5.2 on 2025-04-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Tickets',
            field=models.ManyToManyField(to='cart.ticket'),
        ),
    ]
