# Generated by Django 5.2 on 2025-05-17 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('events', '0002_remove_event_category_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('discount_percent', models.PositiveIntegerField(help_text='e.g., 10 for 10%')),
                ('active', models.BooleanField(default=True)),
                ('valid_until', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='events.event')),
            ],
        ),
    ]
