# Generated by Django 5.2 on 2025-05-17 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartmodel_paid_cartmodel_total_price_ticket_paid_and_more'),
        ('events', '0002_remove_event_category_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='cart.discountcode'),
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='event',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='event',
            field=models.ManyToManyField(related_name='discount_codes', to='events.event'),
        ),
    ]
