# Generated by Django 5.2 on 2025-04-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_cart_cartmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='Tickets',
            new_name='tickets',
        ),
    ]
